#!/bin/bash
# ===================================
# create-pr.sh
# PR 自動生成スクリプト（WorkTree連動）
# ===================================

set -euo pipefail

BRANCH=$(git branch --show-current)
BASE="${1:-main}"
ISSUE_NUMBER="${2:-}"
REPO="Kensan196948G/ZeroTrust-ID-Governance"

if [[ "$BRANCH" == "main" ]]; then
  echo "Error: main ブランチから直接 PR を作成できません"
  exit 1
fi

BODY="$(cat <<'BODY_EOF'
## 📋 Summary
Auto-generated by ClaudeOS v4

## 🔧 Changes
- Implementation changes on this branch

## 🧪 Test Results
- [ ] pytest: pending
- [ ] ruff lint: pending
- [ ] mypy: pending
- [ ] Next.js build: pending

## 🔒 Security
- [ ] No secrets exposed
- [ ] No SQL injection risks
- [ ] No XSS vulnerabilities

## 📊 CI
- GitHub Actions CI: pending

## 🎯 Impact
- Scope: Limited to this feature branch
- Risk: Low

## 📌 Remaining Tasks
- See linked issues

BODY_EOF
)"

if [[ -n "$ISSUE_NUMBER" ]]; then
  BODY="${BODY}

## 🔗 Related Issues
Closes #${ISSUE_NUMBER}"
fi

PR_URL=$(gh pr create \
  --repo "$REPO" \
  --title "feat: $BRANCH" \
  --body "$BODY" \
  --base "$BASE" \
  --head "$BRANCH" \
  --draft 2>&1)

echo "PR created: $PR_URL"

# Project ステータスを Verify に更新
if [[ -n "$ISSUE_NUMBER" ]]; then
  bash "$(dirname "$0")/project-sync.sh" "$ISSUE_NUMBER" "Verify" || true
fi
