#!/bin/bash
# ===================================
# create-issue.sh
# GitHub Issue 自動生成スクリプト
# ===================================

set -euo pipefail

TITLE="${1:-}"
BODY="${2:-Auto-generated by ClaudeOS}"
LABEL="${3:-auto-generated}"
REPO="Kensan196948G/ZeroTrust-ID-Governance"
PROJECT_NUMBER=10

if [[ -z "$TITLE" ]]; then
  echo "Usage: $0 <title> [body] [label]"
  exit 1
fi

# Issue 作成
ISSUE_URL=$(gh issue create \
  --repo "$REPO" \
  --title "$TITLE" \
  --body "$BODY" \
  --label "$LABEL" 2>&1)

echo "Created: $ISSUE_URL"

# Project に追加
gh project item-add "$PROJECT_NUMBER" --owner Kensan196948G --url "$ISSUE_URL" 2>/dev/null || true

# Issue 番号を抽出して Backlog に設定
ISSUE_NUMBER=$(echo "$ISSUE_URL" | grep -oE '[0-9]+$')
if [[ -n "$ISSUE_NUMBER" ]]; then
  bash "$(dirname "$0")/project-sync.sh" "$ISSUE_NUMBER" "Backlog" || true
fi

echo "Issue created and added to project: $ISSUE_URL"
